[tool.poetry]
authors = ["Tony Wu <tonywu6@protonmail.com>"]
description = "Notebook suite for SecretFlow"
name = "secretnote"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8, <3.11"
secretflow = "1.0.0b3"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
ipython = ">=8.12"
jupyterlab = "^4.0.5"
pytest = "^7.4.1"
ruff = "^0.0.287"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.pytest.ini_options]
pythonpath = ["pyproject/src"]

[tool.black]
extend-exclude = """
_pb2\\.pyi?
| _pb2_grpc\\.pyi?
"""
line-length = 88
target-versions = ["py38", "py39", "py310"]

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "B", "I"]
src = ["pyproject/src", "pyproject/tests"]

[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__"]
include = ["pyproject/src"]
reportGeneralTypeIssues = "information"
reportOptionalMemberAccess = "information"
