services:
  alice:
    image: 'secretflow/secretnote:1.6.1-amd64'
    platform: linux/amd64
    environment:
      - SELF_PARTY=alice
      - PORT=8090
    ports:
      - 8090:8090
    volumes:
      - ./alice:/root/workspace

  bob:
    image: 'secretflow/secretnote:1.6.1-amd64'
    platform: linux/amd64
    environment:
      - SELF_PARTY=bob
      - PORT=8092
    ports:
      - 8092:8092
    volumes:
      - ./bob:/root/workspace
