name: 'Build (Temporary)'

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: secretflow/web-ci/.github/actions/ci-setup@main
        with:
          node-version: '18'
          python-version: '3.8'

      - name: Build
        run: pnpm run ci:build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            packages/*/dist/**
            pyprojects/*/dist/**
